### ISSUE TITLE
Admin dio bloga TODO

### ISSUE THREAD

**Issue by br0wn** [fgobin/blog-symfony#2]
1. Dodati WYSIWYG editor kod kreiranja/editiranja bloga. [Ovdje](http://www.1stwebdesigner.com/10-best-wysiwyg-text-and-html-editors-for-your-next-project/) je nekolicina navedena, preporucam CKEditor ili TinyMCE.
2. Napraviti da se mogu uploadati slike kod kreiranja/editiranja bloga.
3. Stilizirati admin koristeći [Twitter bootstrap](http://getbootstrap.com/)

**Comment by fgobin** [comment]
Problem zatvoren jer 3. već postoji kao zasebni problem, a prva dva su riješena.
