### ISSUE TITLE
Struktura html-a prema Bootstrapu

### ISSUE THREAD

**Issue by nenadom** [fgobin/blog-symfony#5]
Trenutno je html za dosta templateova (npr [ovaj](https://github.com/fgobin/blog-symfony/blob/master/src/Blogger/BlogBundle/Resources/views/Page/index.html.twig) i [ovaj ovdje](https://github.com/fgobin/blog-symfony/blob/master/src/Blogger/BlogBundle/Resources/views/Blog/show.html.twig)) neprilagođeno bootstrap [grid](http://getbootstrap.com/css/#grid) sistemu. Cijela struktura je dobro opisana na njihovoj stranici.
Ukratko, `container`class bi se trebao koristiti kao glavni parent sadržaja, `row`leži unutar containera i vertikalno dijeli sadržaj, a `col-` horizontalno dijeli sadržaj, s tim da je sav sadržaj u načelu u `col-`.
Otprilike:
- `container`
  - `row`
    - `col-xs-4`
      - `[content]`

Nestanje je moguće, ali `container`, `row` i `col-` se ne koriste na istom elementu.
Trebalo bi prepraviti sve templateove, i paziti da ubuduće budu pravilno strukturirani. Za sva pitanja sam na raspolaganju, komentar ili mail

**Comment by fgobin** [comment]
Jeli se može to ovako napraviti kad već imamo nasljeđivanje templatea: 
U base.html.twig imamo: 
- container
  - row
    - col-md-9  -- block body

A zatim u bloku body
- row 
  - col-md-6 za lijevi dio
  - col-md-6 za desni dio

Je li takvo ugnježđivanje dozvoljeno?

**Comment by nenadom** [comment]
Je. Bootstrapov grid sistem podržava takvu vrstu nestinga http://getbootstrap.com/css/#grid-nesting
